[Font]
# path = "/home/simon/dotfiles/fonts/.local/share/fonts/arial.ttf"
size = 12.0

[Icons]
entry = ''
# defaults to false if omitted
entry_icon = true

[Colors]
text = "#ffffff"
text_aux = "#888888"
accent = "#333333"
background = "#1a1a1a"

[Window]
width = 300
height = 250
# corner radius of ui elements
# (corners of the windows themselves need
# to be set up seperately using picom)
elem_cnr_rad = 5
row_height = 35

[Misc]
search_hint = "Search..."
# terminate kast automatically after
# a set amount of seconds (0 = disabled)
# if this field is omitted or invalid it
# will default to 20 seconds
timeout = 20

# both devicons and emojis are valid
# for the icon variable
[[App]]
name = "Gimp"
icon = ''
path = "gimp"

[[App]]
name = "Vial"
icon = ''
path = "/home/simon/AppImages/Vial-v0.7.5.AppImage"

[[App]]
name = "Set timer (30 sec)"
icon = ''
path = "/home/simon/dotfiles/scripts/timer-30-sec.sh"

[[App]]
name = "Firefox"
icon = ''
path = "firefox"

[[App]]
name = "Alacritty"
icon = ''
path = "alacritty"

[[App]]
name = "Files"
icon = ''
path = "pcmanfm"
